const WS_EVENT = {
  DEFAULT_CONNECTION: "connection",
  INCOMING: {
    DISCONNECT: "disconnect",
    HOST_JOINED_ROOM: "HOST_JOINED_ROOM",
    HOST_STARTING_GAME: "HOST_STARTING_GAME",
    HOST_START_ROUND: "HOST_START_ROUND",
    HOST_START_SHAKE_ROUND: "HOST_START_SHAKE_ROUND",
    HOST_SHAKE_DONE: "HOST_SHAKE_DONE",
    PLAYER_JOIN: "PLAYER_JOIN",
    SHAKE_COUNT_UP: "SHAKE_COUNT_UP",
    SUBMIT_ANSWER: "SUBMIT_ANSWER",
    SUBMIT_VOTE: "SUBMIT_VOTE",
  },
  OUTGOING: {
    FAILED_TO_JOIN_ROOM: "FAILED_TO_JOIN_ROOM",
    LOBBY_PLAYERS_UPDATED: "LOBBY_PLAYERS_UPDATED",
    PLAYER_ANSWER_RECEIVED: "PLAYER_ANSWER_RECEIVED",
    PLAYER_VOTE_RECEIVED: "PLAYER_VOTE_RECEIVED",
    PLAYER_DISCONNECTED: "PLAYER_DISCONNECTED",
    SHAKE_COUNT_UP: "SHAKE_COUNT_UP",
    SHAKE_RESULTS: "SHAKE_RESULTS",
    SHOW_PLAYER_POINTS: "SHOW_PLAYER_POINTS",
    SHOW_SHAKE_INSTRUCTIONS: "SHOW_SHAKE_INSTRUCTIONS",
    START_GAME: "START_GAME",
    START_SHAKING: "START_SHAKING",
    START_VOTING_PHASE: "START_VOTING_PHASE",
    SUCCESSFULLY_JOINED_ROOM: "SUCCESSFULLY_JOINED_ROOM",
    VOTING_RESULTS: "VOTING_RESULTS",
    WAIT_FOR_VOTES_ON_YOUR_PROMPT: "WAIT_FOR_VOTES_ON_YOUR_PROMPT",
  },
};

export default WS_EVENT;
