export function getRandomPG13Prompt() {
  return prompts[Math.floor(Math.random() * prompts.length)];
}

const prompts = [
  "A weird thing for the letters in your alphabet soup to suddenly spell out",
  "A great prank to play on a pizza delivery guy",
  "The most surprising thing you could find in the glove box of a rental car",
  "Four-leaf clovers are lucky. But if you find a five-leaf clover...",
  "The only job you would do for free",
  "The most German-sounding word you can invent",
  "The worst name for a country music singer",
  "It would be really weird to have a bobblehead doll of <BLANK>",
  "If you can\u2019t say anything nice...",
  "The title of Bob Saget\u2019s biopic",
  "The perfect time to wear stilts",
  "Little-known fact: In a lifetime, the average person will <BLANK> over 1,000 times while sleeping",
  "A rejected name for tater tots",
  "On the seventh day, God rested. On the eighth day, he <BLANK>",
  "A weird reason to have your car recalled",
  "You should always wear a helmet when <BLANK>",
  "Few remember Michelangelo\u2019s <i>Mona Lisa 2</i> which was a painting of <BLANK>",
  "Something a kangaroo might search for on Google",
  "A bad substitute for a surfboard",
  "Where would you live if you were two inches tall?",
  "What to do when a really tall person sits in front of you at the movie theater",
  "An entry in teenage Tarzan\u2019s diary: \u201cToday, I <BLANK>\u201d",
  "The absolute best place to hide your house key",
  "A strange place to go to while wearing a ski mask",
  "What those giant Easter Island heads are thinking",
  "So, how do you like it?",
  "What ruined Hannibal \u201cThe Cannibal\u201d Lecter\u2019s credit score?",
  "What the lamest Transformer would morph into",
  "You would gladly give money to someone on the street if they asked \u201cCan you spare some change so I can <BLANK>?\u201d",
  "SPOILER ALERT: The big plot twist in <i>The Sisterhood of the Traveling Pants 7</i> is that the pants <BLANK>",
  "You know you\u2019re a spoiled brat when your tree house has a <BLANK>",
  "What King Kong is most self-conscious about",
  "The only reason to ever play a banjo",
  "The big conspiracy that nobody even suspects is <BLANK>",
  "How Jonah passed the time stuck inside a giant fish",
  "Something that the Keebler Elves chant during a strike",
  "The title of the most popular TV show in North Korea, probably",
  "A quick way to annoy Pat Sajak while playing <i>Wheel of Fortune</i>",
  "The title of a National Public Radio show that would put you to sleep the quickest",
  "Where the missing sock in the dryer ends up going",
  "The worst part about being seven feet tall",
  "A really weird protest sign would be \u201cEnd <BLANK> Now!\u201d",
  "How you can tell your new, all-vegetable diet is working",
  "If Cap\u2019n Crunch ever gets court-martialed, it\u2019ll probably be because he...",
  "Where in the world is Carmen Sandiego? ",
  "The name of a band in which every member plays the spoons",
  "A little-known use for ear wax",
  "The type of life they\u2019ll probably find on Mars",
  "The name of a board game for players age 70 & older ",
  "Bob the Builder probably wouldn\u2019t be as popular with children if he were Bob the <BLANK>",
  "The worst thing to do when a bear is right next to you",
  "Unlike \u201cMaverick\u201d or \u201cIceman,\u201d a really bad Air Force fighter pilot name would be <BLANK>",
  "It would\u2019ve been a much different movie if instead of \u201cPhone home,\u201d E.T. kept saying, \u201c<BLANK>\u201d",
  "A weird way to dry your hair",
  "A new name for the U.S. Congress ",
  "What Adam thought when he first met Eve",
  "What do ceramic garden gnomes do at night?",
  "A mystery that Sherlock Holmes could never solve: The Case of the <BLANK>",
  "The real secret to a happy marriage is...",
  "A rejected name for the game Yahtzee",
  "The best thing to blurt out in order to ruin a beautiful sunset",
  "A mobster\u2019s pet peeve",
  "You know you\u2019re comfortable in a relationship when you ask your significant other to <BLANK>",
  "The best line to say when you come out of a 10-year coma ",
  "The real reason Mr. Clean is grinning",
  "The best name to give an ugly baby",
  "The first thing Abraham Lincoln would do if he came back from the dead",
  "Come up with a <i>TMZ</i> celebrity headline from five years in the future",
  "What the roller coaster attendant is actually saying during his mumbled preamble before the ride",
  "An ad slogan for cardboard: \u201cNow with more <BLANK>\u201d ",
  "The most annoying person in a movie theater would <BLANK>",
  "A rejected Monopoly game piece ",
  "A terrible sign-off line for a newscaster",
  "A good sign that you may be a ghost",
  "The creepiest thing to whisper in somebody\u2019s ear as you\u2019re hugging them",
  "A better name for the ukulele",
  "What happens when Wile E. Coyote finally catches The Road Runner?",
  "What the Queen\u2019s Guard is secretly thinking as they just stand there",
  "The worst part about having a mustache",
  "An awkward thing to hear from the person pooping in the bathroom stall next to you",
  "A quick way to save money on grocery bills",
  "A good sign you\u2019re never going to be a professional football player",
  "The worst Viking: Eric the <BLANK>",
  "How they really select the next Pope",
  "The name of a new cologne inspired by celebrity chef Guy Fieri",
  "A great way to quickly get out of credit card debt",
  "The worst upstairs neighbors would be people that <BLANK>",
  "The weirdest message your cat could write out to you in its litter box",
  "A good nickname for your abs",
  "The lesser-known sequel to <i>Old Yeller</i>: <i>Old Yeller 2: <BLANK></i>",
  "A horrible pick-up line",
  "The best way to keep a co-worker from stealing your lunch",
  "The least scary horror movie: <i>Night of the <BLANK></i>",
  "The worst thing to find when you move into a new house",
  "The worst carnival prize you could win",
  "The most unusual environmental cause is \u201c<BLANK> the Whales\u201d",
  "The only thing worse than standing in a really long line is standing in a really long line for <BLANK>",
  "You wake up 100 years in the future and are shocked to find <BLANK>",
  "A weird thing for a preacher to say to end every sermon",
  "A rejected tourism slogan for Des Moines, Iowa: \u201cHome of the <BLANK>\u201d",
  "A forgotten book in the classic Harry Potter series: <i>Harry Potter and the <BLANK></i>",
  "The weirdest thing a restroom attendant could offer you",
  "The worst Thanksgiving Day balloon would be a giant, inflatable <BLANK>",
  "The big, crazy twist at the end of the next M. Night Shamalayan movie: He was <BLANK> the whole time!",
  "Most people know it as The Big Apple, but a lesser-known nickname for New York is The Big <BLANK>",
  "The next best thing to chew when you\u2019re out of gum",
  "You know you\u2019re in a very weird fast food restaurant when the cashier asks, \u201cDo you want <BLANK> with that?\u201d",
  "It\u2019s not the heat. It\u2019s not the humidity. It\u2019s the <BLANK>",
  "It\u2019s incredibly rude to <BLANK> with your mouth open",
  "You never have a <BLANK> when you need one",
  "<i>The Empire Strikes Back</i> would\u2019ve been ruined if Darth Vader said \u201cLuke, I am <BLANK>\u201d",
  "The worst 1960s teen movie was definitely <i><BLANK> Beach</i>",
  "The most disgusting breakfast cereal: <BLANK> Flakes",
  "In the next big sports scandal, we\u2019ll find out that <BLANK>",
  "Worse than global warming, the real threat to humanity is global <BLANK>",
  "Forget dogs. What is really man\u2019s best friend?",
  "How you can tell it\u2019s a doctor\u2019s first day on the job",
  "The worst name for an all-girl band",
  "A bad thing to say to your date\u2019s parents",
  "Pitch the worst video game idea in five words or less",
  "How embarrassing for you. You just <BLANK>",
  "The worst mistake you could make while streaming on Twitch.tv",
  "The worst song to do pairs figure skating to",
  "What landed you in the emergency room this time?",
  "The worst thing to say during a job interview",
  "A magazine category that hasn\u2019t been invented yet",
  "The top 3 ingredients in garbage truck juice",
  "A really bad superhero power",
  "The worst thing to put on a pizza",
  "If evolution is true, then why hasn\u2019t <BLANK> evolved into <BLANK>?",
  "R2D2\u2019s biggest complaint",
  "Come up with a bad tourism slogan for the Old Faithful geyser",
  "The worst possible choice for the person on the new $20 bill",
  "A little-known lyric in the original draft of the \u201cStar-Spangled Banner\u201d",
  "The best thing to shoot out of a cannon",
  "The winners on <i>The Bachelor</i> get a rose. The losers should get <BLANK>",
  "From the creators of \u201cWhack-a-Mole\u201d comes the new game \u201c<BLANK>-a-<BLANK>\u201d",
  "The title of a never-released Jimmy Buffett song",
  "The worst thing to hear from your GPS: \u201cIn two miles, <BLANK>\u201d",
  "The weirdest sentence a judge could impose",
  "A good use for toenail clippings",
  "A fitting punishment for people who double-dip their chips",
  "America\u2019s energy crisis would be over if we made cars that ran on <BLANK>",
  "Something it\u2019d be fun to watch ride an escalator ",
  "A high school superlative you don\u2019t want to win: Most Likely To <BLANK>",
  "A rejected title for <i>Moby Dick</i>",
  "Something you do not want to find under your hotel bed",
  "You know your doctor has gone insane when he tells you to make sure you <BLANK> at least once a day",
  "The worst part about being a Teenage Mutant Ninja Turtle",
  "A sign that your kid isn\u2019t good at sports",
  "The first sign that you\u2019re no longer cool",
  "A video sure to get over 150 million views on YouTube would be \u201cChickens <BLANK>\u201d",
  "A surprising thing to find stuck to the bottom of your shoe",
  "The worst thing that could follow \u201cHoney-Roasted\u201d",
  "Why are geese such jerks?",
  "A sign that you\u2019re a bad teacher",
  "The worst breakfast: pancakes shaped like <BLANK>",
  "What bears dream about all winter",
  "A good sign that you\u2019ve drunk too much Mt. Dew",
  "What\u2019s in the box? WHAT\u2019S  IN THE BOX?!",
  "The manliest way to start a conversation",
  "What the abominable snowman does when he\u2019s bored",
  "A good alternative for ping-pong paddles",
  "You know you\u2019re a chocoholic when...",
  "The worst reason to use a time machine",
  "Something you should not do while crowdsurfing",
  "What those bolts in Frankenstein\u2019s neck are for",
  "What Waldo from \u201cWhere\u2019s Waldo?\u201d says to himself in the mirror",
  "The worst road trip would start with someone <BLANK>",
  "A creepy thing to write in your email signature line",
  "The only five words in your obituary in the newspaper",
  "What\u2019s the U.S. government really hiding in Area 51?",
  "The worst advice an IT guy could give",
  "A really bad name for an apartment complex: \u201c<BLANK> Place\u201d",
  "What should we do with all of that plastic that won\u2019t disintegrate?",
  "One thing that the rich truly enjoy is diamond-encrusted <BLANK>",
  "The best part of turning 100 years old",
  "The lesser-known other way to find the Wizard of Oz: Follow the <BLANK> Road",
  "Forget coffee. Don\u2019t talk to me until I\u2019ve had my <BLANK>",
  "Odd new shampoo instructions: \u201cLather, Rinse, <BLANK>, Repeat.\u201d",
  "The worst magic trick",
  "The lost Hemingway book: <i>The Old Man and the <BLANK></i>",
  "The title of a podcast you would never ever listen to",
  "The name of a new, terrifying species of spider",
  "The most annoying co-worker would constantly <BLANK>",
  "A surefire way to ruin Christmas",
  "The name of the worst baby doll",
  "\u201cDon\u2019t blame me, I voted for <BLANK>.\u201d",
  "The name of a fast food restaurant in the Stone Age",
  "Dodgeball would be an even better sport if <BLANK> were allowed",
  "A <BLANK> a day keeps the doctor away",
  "What is the Abraham Lincoln statue thinking while he\u2019s sitting there in the Lincoln Memorial?",
  "Instead of \u201cCheese!\u201d the worst family photographer would tell you to say, \u201c<BLANK>!\u201d",
  "The title of a college admission essay that would definitely get rejected",
  "Something Big Bird will confess on his deathbed",
  "What you would expect Justin Bieber\u2019s line of fragrances to smell like",
  "The last thing you\u2019d want to find in your air ducts",
  "The worst college football team: The Fighting <BLANK>",
  "A terrible name for a dragon",
  "In the future, moviegoers will flock to see <i>Jurassic Park 10: <BLANK></i>",
  "The worst way to unclog a toilet",
  "Something that\u2019s been hiding in the background in every episode of <i>Friends</i>",
  "We should combine Minnesota and Wisconsin and call them <BLANK>",
  "The name of a cable network that no one watches",
  "If the groundhog \u201ckind of\u201d sees his shadow, it\u2019s six weeks of <BLANK>",
  "What\u2019s really destroying the ozone layer?",
  "You know you\u2019re famous when...",
  "The absolute worst moment for a bird to poop on you",
  "A weird thing for someone to frame and hang on the wall",
  "The best thing to yell while going over Niagara Falls in a barrel ",
  "What you don\u2019t want to hear from the passenger next to you at the start of a 20-hour flight",
  "Why ducks really fly south in the winter",
  "Where Charlie Brown winds up at age 45",
  "What a frog would say to his psychiatrist",
  "What is the Loch Ness Monster, really?",
  "The Pyramids would be even more impressive if they contained <BLANK>",
  "What Sam Elliott probably nicknames his mustache",
  "The worst theme for your kid\u2019s first dance recital",
  "The worst combination of two actors that could possibly star in the next season of <i>True Detective</i> together",
  "It\u2019s disappointing to put together a 1,000 piece puzzle and realize it\u2019s just a picture of <BLANK>",
  "The name of a law firm you shouldn\u2019t hire",
  "The worst thing to find frozen in an ice cube",
  "Something you don\u2019t expect to see when you spy on your neighbors",
  "An experiment mice actually like having performed on them",
  "A double rainbow doesn\u2019t have gold at the end of it. Instead, it has <BLANK>",
  "The best shirt to wear next to somebody who\u2019s wearing an \u201cI\u2019m with stupid\u201d T-shirt",
  "The worst thing a plastic surgeon could say after he botched your surgery: \u201cI\u2019m sorry, I accidentally <BLANK>\u201d",
  "The worst advice your boxing coach could give you",
  "What an alarm clock could say that would wake you right up",
  "A weird thing to hear from your doctor: \u201cI\u2019m afraid you have <BLANK>\u201d",
  "In a shocking poll, it was discovered that three out of four Americans <BLANK>",
  "The most common thing you\u2019d hear if you could read people\u2019s thoughts",
  "The name of a hairstyle that will never catch on",
  "A bad name for an Italian restaurant",
  "A realistic, honest fast-food slogan",
  "A good sign that you\u2019ve drunk too much Mt. Dew",
  "What bears dream about all winter",
  "The worst breakfast: pancakes shaped like <BLANK>",
  "A sign that you\u2019re a bad teacher",
  "If a genie gives you three wishes, the best things to wish for are: 1) a billion dollars, 2) eternal life, and 3) <BLANK>",
  "The worst charity: Save the <BLANK>",
  "Little-known fact: An unaired episode of <i>The Brady Bunch</i> had the family dealing with <BLANK>",
  "The futuristic invention you can\u2019t wait to see exist",
  "What\u2019s really at the center of the Earth?",
  "Invent a new word for the toilet that sounds like it\u2019s from Shakespeare",
  "Safety tip! Don\u2019t eat a half hour before you <BLANK>",
  "The real way you can tell an alligator from a crocodile",
  "A very unnecessary surgery",
  "Survival tip! Start a fire by rubbing <BLANK>",
  "Helpful advice you would give to Super Mario",
  "In the future, scientists discover that the secret to eternal youth is <BLANK>",
  "Something you shouldn\u2019t use a chainsaw for",
  "A surprising purchase on Willy Wonka\u2019s credit card statement",
  "The worst album: \u201c<BLANK> Sings the Blues\u201d",
  "A really stupid idea for a phone app (that would still make you millions of dollars)",
  "The name of a new game show that sounds terrible",
  "The one thing you wish a politician would just say already",
  "A secret way to get stubborn ketchup out of the bottle",
  "The most surprising person to admit to being the Zodiac Killer",
  "A lesson that probably wouldn\u2019t be taught on <i>Sesame Street</i>",
  "Something you promise to yell if you win this game",
  "A creepy thing to find scribbled onto a dollar bill",
  "If you don\u2019t have extra money, an odd thing to use as a tip for your waiter",
  "The name of the next hot boy band",
  "A terrible name for a king",
  "A sure sign that a drifter has been secretly living in your house",
  "The name of a new U.S. state you would never visit",
  "The one thing that isn\u2019t better dipped in chocolate",
  "Like \u201cdinger,\u201d \u201cgrand salami,\u201d and \u201cjack,\u201d come up with a new slang term for a home run in baseball",
  "A terrible vacation idea: going to visit The Museum of <BLANK>",
  "A great gag gift would be an exploding <BLANK>",
  "The official medical term for belly button lint (probably)",
  "A surprising thing to hear in a nature documentary",
  "The years 2011 to 2020 will be remembered as \u201cThe <BLANK> Age\u201d",
  "An inventive way to get rid of head lice",
  "Little-known fact: the scariest animal in the world is the <BLANK> cobra",
  "A bad name for a brand of hot sauce",
  "An excuse to avoid riding the mechanical bull",
  "What Big Foot complains about to his therapist the most",
  "The worst warning to read on some medicine you just swallowed",
  "A strange poster to hang in a college dorm room",
  "Never pay more than $3 for <BLANK>",
  "The name of a really bizarre diet that just never caught on",
  "The most popular T-shirt slogan in Mississippi, probably",
  "The hit song from the Broadway show <i>Fart: The Musical</i>",
  "A ridiculous government agency that no one knows about: The Department of <BLANK>",
  "The best thing about being thrown into a volcano",
  "The world\u2019s most boring video game",
  'New requirement at amusement parks: \u201cYou must be this <BLANK> to ride"',
  "You probably shouldn\u2019t hire a moving company called <BLANK>",
  "The weirdest combination of three items that you could buy at the store",
  "The worst halftime show: The <BLANK> Dancers",
  "What\u2019s really in a camel\u2019s hump?",
  "The most obnoxious name someone could give their kid",
  "Something that is probably on Nicolas Cage\u2019s \u201cTo Do\u201d list",
  "The newest health food: <BLANK> juice",
  "HR would probably get the most complaints on \u201cBring your <BLANK> to work\u201d day",
  "A lesser-known Knight of the Round Table: Sir <BLANK>",
  "A Socrates quote that nobody bothered to write down",
  "Why is the sky blue?",
  "The best way to catch a leprechaun",
  "The worst things to juggle",
  "Turns out, the meaning of life is <BLANK>",
  "The worst tattoo to have on your forehead",
  "A mean text you would send to break up with a Muppet",
  "What really cracked the Liberty Bell?",
  "A weird photo to keep in your wallet",
  "An odd painting to hang above your bed",
  "A poor substitute for a necktie",
  "The perfect day off is just twelve straight hours of <BLANK>",
  "The worst Vegas casino: <BLANK> Palace",
  "Something awful to hold in your mouth for an hour",
  "A great way to start a conversation with a weird loner on the subway",
  "A hip, new advertising slogan for socks",
  "Really awful cheerleaders would yell \u201c<BLANK>!\u201d",
  "Why should you never turn your back on a penguin?",
  "The reason Pluto isn\u2019t a planet anymore",
  "The biggest issue facing the town of Margaritaville ",
  "The least appetizing name for a restaurant",
  "Something you should not say in front of a parrot",
  "Something you should not put in your kid\u2019s sandbox",
  "What the boogeyman is afraid of",
  "A bad name for a hospital",
  "Something you do not want to do while standing in a police lineup",
  "Where\u2019s Jimmy Hoffa? ",
  "An odd casting choice would be Clint Eastwood as <BLANK>",
  "After the Heimlich Maneuver, the second-best way to stop someone from choking",
  "A rejected safety technique for when you catch fire was to \u201cstop, drop, and <BLANK>\u201d",
  "The difference between Grade A beef and Grade B beef",
  "The weirdest room you could see in an airport would be one specifically designated for <BLANK>",
  "If you really want to impress the Olympic diving judges, try a dive that involves <BLANK>",
  "What you think the word \u201cpandiculation\u201d means",
  "A body of water you definitely shouldn\u2019t swim in",
  "Something fun to ask the old wise man on top of the mountain",
  "A rejected tagline for <i>Star Trek</i> instead of \u201cSpace: the final frontier\u201d was \u201cSpace: <BLANK>\u201d",
  "How would YOU fix the economy?",
  "The hardest part about living in a submarine",
  "If you really, really love something, let it <BLANK>",
  "A name for a really scary swamp: <BLANK> Swamp",
  "The name of the music playlist that will definitely put an end to the party",
  "A bad name for a water park",
  "A polite way to say \u201cbooger\u201d",
  "A fun outfit to dress up the statue of David in",
  "Kennedy\u2019s original speech said, \u201cAsk not what your country can do for you, ask <BLANK>\u201d",
  "What the hot trend in weddings will be in the year 2046",
  "Something fun to scream at a farmer\u2019s market",
  "Mother Teresa\u2019s deepest secret ",
  "The most creative thing you can make entirely out of boogers",
  "An ill-advised outfit to wear to your first day at a new job",
  "Sleepwalking can be a problem but it\u2019s not as bad as sleep<BLANK>",
  "In the future, RoboCop actually retires from the police force and becomes Robo-<BLANK>",
  "What to do when your parachute fails",
  "Something people used to do for fun before electricity",
  "The most embarrassing crime to get caught committing",
  "The name that cavemen probably gave to diarrhea",
  "The worst person to share a hot tub with",
  "A peculiar thing to see in a Help Wanted ad would be \u201cHelp Wanted: <BLANK>\u201d",
  "What mustaches SHOULD be called",
  "The worst pizza is <BLANK>-style pizza",
  "A real weirdo would fall asleep to the sounds of <BLANK>",
  "The name of a dog food brand you probably should not buy",
  "Come up with a name for a generic brand of hot dogs that you probably shouldn\u2019t buy",
  "Everything tastes better with <BLANK>",
  "Life hack! Lower your heating bills by...",
  "The worst thing that could crawl out of your toilet",
  "The worst advice a doctor could give",
  "Something a weatherman might yell if he completely snapped during the weather forecast",
  "A great birthday present for your worst enemy",
  "The name of a painting Michelangelo was ashamed he created",
  "A clever thing for James Bond to say as he throws someone out of an airplane",
  "No one would guess this is where the treasure is buried",
  "The secret to a healthy head of hair",
  "A strange thing to read on a door mat",
  "The secret to a great marriage",
  "What really happens if you stare at the sun too long",
  "A prank the Supreme Court Justices probably play on each other",
  "What the Easter Bunny does with his free time",
  "A little known-perk of being U.S. president",
  "A horrible charity: <BLANK> for Tots",
  "A word that should be in the dictionary but isn\u2019t",
  "A really odd thing to say on your deathbed",
  "The Four Horsemen wouldn\u2019t be as scary if they were the Four <BLANK>men of the Apocalypse",
  "It\u2019s illegal to yell \u201cFire!\u201d in a crowded theater, but it should also be illegal to yell, \u201c<BLANK>!\u201d",
  "A good name for a pet cemetery",
  "A new word for people that drive too slow in the fast lane",
  "The perfect name for a second head that sprouts on your shoulder",
  "The worst material from which to make a pair of pajamas",
  "Queen Elizabeth\u2019s deepest, darkest secret",
  "Come up with a slogan for the Russian Tourism Board",
  "The best part about being Donald Trump",
  "Tip: Never eat at a place called \u201cKentucky Fried <BLANK>\u201d",
  "Sometimes John Travolta wildly mispronounces names. How might he wildly mispronounce his own name?",
  "The worst toy store: Build-A-<BLANK> Workshop",
  "The weirdest thing you can buy at the Vatican gift shop",
  "The worst invention that starts with \u201cSpray-On\u201d",
  "The name of a species of dinosaur you wouldn\u2019t want to meet",
  "Something overheard at the Last Supper",
  "A possible entry in Gary Busey\u2019s dream journal: \u201cTonight I dreamed <BLANK>\u201d",
  "Something you can make out of body hair",
  "The worst way to fly: <BLANK> Airlines",
  "So... what was that movie <i>Birdman</i> about anyway?",
  "A great pet name for a parasitic worm that lives in your ear",
  "An idea for Lady Gaga\u2019s next crazy outfit: a <BLANK> dress",
  "Little-known fact: Over the course of a lifetime, an average person accidentally eats ten <BLANK>",
  "Something you probably shouldn\u2019t try to sell on eBay",
  "The worst air freshener scent",
  "A terrible thing to sign on the cast of your friend\u2019s broken leg",
  "It would be awesome to win <i>Jeopardy</i> with the phrase, \u201cWhat is <BLANK>, Alex?\u201d",
  "A sign you probably shouldn\u2019t put up in your yard",
  "A bad title for a self-help book",
  "An unusual \u201cSpecial Skill\u201d to include on your resume",
  "What kittens would say if they could talk",
  "A strange thing to keep as a pet",
  "The worst thing about Canada",
  "You should never share <BLANK> with someone else",
  "The grossest thing you could find at the bottom of a swimming pool",
  "The sound a tree actually makes when it falls and no one is around to hear it",
  "You need three things to live: food, water, and <BLANK>",
  "A good use for toenail clippings",
  "What you would do with two free hours and a flamethrower",
  "The worst name for an SUV",
  "New sport idea: professional <BLANK>",
  "Trash talk you would hear at a chess meet",
  "Something you shouldn\u2019t stuff with cheese",
  "Something pirates probably aren\u2019t very good at",
  "Everyone knows there\u2019s no such thing as <BLANK>",
  "A completely untrue rumor about Alvin from Alvin and the Chipmunks",
  "You should never <BLANK> and <BLANK> at the same time",
  "The worst thing about being a billionaire",
  "Briefly describe your imaginary friend",
  "New movie idea: <i>The Muppets Take <BLANK></i>",
  "What you call a baby sasquatch",
  "What is a tree thinking all day?",
  "The best use for a leftover meatball",
  "A bad reason to call 911",
  "The best way to quickly blow a million dollars",
  "Your first decree after being named Supreme Ruler of Earth",
  "The worst thing to receive for trick-or-treat",
  "Come up with a name for a kooky ostrich who solves mysteries",
  "A phrase you would love to hear Morgan Freeman say",
  "USA! USA! America is still number one in...",
  "An Olympic sport that never made it: Synchronized <BLANK>",
  "The government should legalize...",
  "The first thing to do if you\u2019re attacked by a shark",
  "The worst thing to find growing on your neck",
  "A little-known fact about the Jolly Green Giant",
  "The perfect meal would be a <BLANK> stuffed in a <BLANK> stuffed in a <BLANK>",
  "What\u2019s black and white and red all over?",
  "New show idea: <i>America\u2019s Next Top <BLANK></i>",
  "It never ends well when you mix <BLANK> and <BLANK>",
  "Invent a silly British term for pooping",
  "The best reason to go to Australia",
  "The beauty pageant no one wants to see: Miss <BLANK>",
  "The most boring graffiti you could see in the subway",
  "A slogan to get everyone excited about corn",
  "You never forget your first <BLANK>",
  "Little-known fact: The human body is approximately 80% <BLANK>",
  "Coming soon to a theater near you: Benedict Cumberbatch is <BLANK>",
  "Something you shouldn\u2019t buy at a yard sale",
  "If we only use 10% of our brains, what\u2019s the other 90% doing?",
  "What you want your gravestone to read",
  "The worst menu item that starts with \u201cAll You Can Eat\u201d",
  "A sign you wouldn\u2019t want to see at a seafood restaurant",
  "Something fun to yell during an opera",
  "A group activity at a really bad summer camp",
  "A Girl Scouts cookie name that got rejected because it was just too ridiculous-sounding",
  "The least impressive Boy Scout badge",
  "The worst ringtone for a cell phone",
  "A great nickname for your armpit hair",
  "\u201cKnock, knock!\u201d \u201cWho\u2019s there?\u201d <BLANK>",
  "A Tweet from a caveman",
  "A message found in a bottle floating in the sea",
  "The worst car feature that ends with \u201cholder\u201d",
  "What Chewbacca has really been yelling all these years",
  "The most stereotypical country song title",
  "The best way to survive a bear attack is <BLANK>",
  "The worst name for a funeral home",
  "An angry internet comment on a pet store\u2019s website",
  "The worst name for a rap artist",
  "A rejected shape for Marshmallow Peeps",
  "Something that should never be \u201chomemade\u201d",
  "Three things MacGyver needs to make a bomb",
  "Another use for marshmallows",
  "Another use for gravy",
  "A great way to cure the hiccups",
  "An animal Noah shouldn\u2019t have saved",
  "The biggest secret the government keeps",
  "Something you wouldn\u2019t expect a Ouija board to say",
  "The best way to defeat terrorism is...",
  "Come up with a name for a salad dressing by Lindsay Lohan",
  "The best way to tell if a tomato is ripe",
  "A good post-music career for Justin Bieber",
  "Come up with a name for a sitcom about a bunch of wacky nuns",
  "A completely wrong way to spell \u201cJennifer Aniston\u201d",
  "The 11th Commandment: Thou shalt not...",
  "The best way to scare a burglar",
  "The worst thing to yell while a professional golfer putts",
  "The second thing said on the moon",
  "Something you can only do in a Walmart if no one\u2019s looking",
  "A name for a really cheap hotel",
  "The worst name for a mountain",
  "Why so serious?",
  "The best thing about being really dumb",
  "A thought that keeps Santa Claus awake at night",
  "The real secret to living to age 100",
  "What really happens if you tear off that mattress tag",
  "A bad first line for your presidential inauguration speech",
  "A fun thing to do with a bowl of pudding",
  "Another use for cooked spaghetti",
  "A weird physical way to greet someone",
  "The worst name for a tanning salon",
  "The worst word that can come before \u201cfart\u201d",
  "A bad substitute for a toothbrush",
  "A trick you shouldn\u2019t teach your dog",
  "The worst material with which to make a snowman",
  "A terrible sportscaster catchphrase for when somebody dunks a basketball",
  "The first thing a pig would say if it could talk",
  "The worst shape for an animal cracker",
  "A surprising job entry on Abraham Lincoln\u2019s resume",
  "Something you\u2019d yell to heckle the performing dolphins at Sea World",
  "The worst name for a \u201cbig and tall\u201d store",
  "The name of a shampoo for hippies",
  "A new name for kumquats",
  "An angry review you\u2019d give this game (Quiplash)",
  "The worst thing to wear to your court trial",
  "A rejected crayon color",
  "Graffiti you might find in a kindergarten",
  "The first sign that you\u2019re old",
  "The worst question to ask during a White House tour",
  "Tomorrow\u2019s news headline: \u201cScientists Are Shocked to Discover That <BLANK>\u201d",
  "A terrible talent to have for the Miss America Pageant",
  "Bad advice for new graduates",
  "The best way to tell if someone is dead",
  "A TMZ headline you really want to see",
  "What you hope the Mars Rover finds",
  "Where missing socks go",
  "A rejected phrase for one of those Valentine heart candies",
  "Something that will get you thrown out of a Wendy\u2019s",
  "It would be scary to read on a food package, \u201cMay contain trace elements of <BLANK>.\u201d",
  "A just-so-crazy-it\u2019s-brilliant business idea to pitch on <i>Shark Tank</i>",
  "A terrifying fortune cookie fortune",
  "Something the devil is afraid of",
  "CBS should air a TV show about lawyers who are also <BLANK>",
  "A great thing to yell before jumping out of an airplane",
  "A gift nobody would want: The <BLANK> of the Month Club",
  "A better name for the game Duck Duck Goose",
  "A bad way to remove unsightly chest hair",
  "An unusual theme for a kid\u2019s lunchbox",
  "What the government is hiding from the public in Area 497",
  "What your pancreas tests revealed",
  "A bad, one-word slogan for a presidential campaign",
  "Something you'd make a butler do the moment you hired him",
  "Why did the mortician cross the road?",
  "Something you should never try to heat in the microwave ",
  "A surprising thing to find inside a piñata ",
  "An alternate name for The Mona Lisa",
  "A reason to travel back in time to two weeks ago",
  "If you\u2019d never heard the term \u201cgreat white shark,\u201d what might you call it when you saw one for the first time?",
  "A place where you're not likely to spot Bigfoot",
  "Something you should never say as the captain of a bowling team",
  "The dumbest person in the history of all time ",
  "Another name for the Grand Canyon",
  "Another name for Canada",
  "A bad use for clam chowder",
  '"On the 147th day of Christmas, my true love gave to me..."',
  "The best name for an obese rapper",
  "It would be most awesome for Chuck Norris to fight <BLANK>",
  "A good puck replacement if they run out of pucks in a game of hockey",
  "If animals took over, an exhibit you\u2019d see at the human zoo",
  "A terrible wedding gift",
  "A street name you never see",
  "The first thing that pops into your mind right now",
  "A weapon that should be added to the game Clue",
  "The toy surprise in an Unhappy Meal",
  "Make up a word for the watery substances that come out of a ketchup bottle when you first squeeze it",
  "Make up a name for the space between your nostrils",
  "Italy\u2019s newest tourist attraction: The <BLANK>Tower of Pisa",
  "The worst theme for a pinball machine",
  "The name of Jesus' 13th apostle",
  "Something you don't want to find in your Christmas stocking",
  "A title of a self-help book for rats",
  "The worst thing you could rub all over your face",
  "George W. Bush and Dick Cheney's rap duo name",
  "Something you rarely see used as a car decoration",
  "A historical event that would make a bad theme for a restaurant",
  "The worst thing to try to sell door-to-door",
  "Something you probably shouldn\u2019t bring on a trip across the Sahara desert",
  "What's that stain?",
  "Something you'd love to smash with a wrecking ball",
  "A bad name for a pet goldfish",
  "Life would be so much better if we all lived in <BLANK>",
  "Something it\u2019s not a good idea to put in the overhead bin on an airplane",
  "A weird thing for a bank robber to demand in a hostage situation",
  "Something they will probably never make a series of commemorative stamps for",
  "A club you wish they had in high school",
  "The best prize you could find in a Cracker Jack box",
  "The worst soup flavor: Cream of <BLANK>",
  "A strange place to hold a family reunion",
  "Something you\u2019d sneak into space, if you were an astronaut",
  "What they really found in King Tut\u2019s tomb",
  "The name of that cheese shop you\u2019re going to open some day",
  "The liquid that would make for the worst salad dressing",
  "An unusual motif for a baby\u2019s nursery",
  "Another name for toe jam",
  "A better name for dandruff",
  "A terrible name to have if you\u2019re running for public office",
  "Four out of five dentists agree you should never <BLANK>",
  "Something that would make a creepy replacement for the horses on a merry-go-round",
  "The worst thing to vomit into when you suddenly need to vomit",
  "Make up a word that means \u201cto make up a word\u201d",
  "Like Plutonium or Einsteinium, what would you name the next Periodic Table element they discover?",
  "A bad name for a pirate",
  "Something fun to scream when you win in a game of bingo, other than \u201cBingo!\u201d",
  "A movie that should never be made into a theme park ride",
  "A business or service that shouldn't have a drive-through window",
  "Paul Bunyan\u2019s replacement for Babe The Blue Ox when he dies",
  "The worst flavor for a sno-cone",
  "What Smokey the Bear does when he\u2019s not fighting forest fires",
  "Combine any two words to make a fun, new made-up word",
  "A lesser-known ingredient in most microwave pizza pockets",
  "A great place to hide an Easter egg",
  "A trick you\u2019d like to see a poodle do",
  "A better name for the Washington Monument",
  "You never know when you\u2019re going to need insurance. You could wake up tomorrow and <BLANK>",
  "The worst thing to overhear during your surgery",
  "A bad name for a brand of bottled water",
  "How do you like it?",
  "Come up with a new dessert that contains the name of a U.S. state",
  "The first and second rules of Fight Club are \u201cDon\u2019t talk about Fight Club,\u201d but what\u2019s the 387th rule of Fight Club?",
  "A terrible food truck would be one that goes around selling only <BLANK>",
  "A reason to get into a fist fight with a koala bear ",
  "Little-known fact: the fourth Wise Man gave baby Jesus the worst gift of all: <BLANK> ",
  "A theme for a desk calendar that wouldn\u2019t sell very well ",
  "The worst thing you could stick in a toaster ",
  "The worst Halloween costume for a young child",
  "\u201cThis just in! A <BLANK> has won the election and will become the new governor of Texas.\u201d ",
  "A better name for the human bladder",
  "Surprising first words for your baby to speak",
  "A good name for a dog country singer",
  "A lawn decoration sure to make the neighbors mad",
  "The worst thing to say when trying to adopt a pet",
  "Fun thing to do if locked in the mall overnight",
  "The worst person to receive a sponge bath from",
  "People wouldn\u2019t respect He-Man as much if, to gain his power, he held up his sword and shouted \u201c____________________\u201d",
  "Pants would be a whole lot better if they <BLANK>",
  "A little-known way to get gum out of your hair",
  "The most awesome Guinness World Record to break",
  "It\u2019s bad to be buried alive. It\u2019s worse to be buried alive with <BLANK>.",
  "Something that would not work as well as skis",
  "What to say to get out of jury duty",
  "A rejected name for a ship in the U.S. Naval Fleet: the USS <BLANK>",
  "A rejected title for <i>The Good, The Bad and the Ugly</i> was <i>The Good, the Bad and the <BLANK></i>",
  "Little-known fact: The government allows peanut butter to contain up to 10% <BLANK>",
  "A good sign that your house is haunted",
  "A bad occupation for a robot to have",
  "A sequel to the painting \u201cDogs Playing Poker\u201d",
  "The Tooth Fairy\u2019s other job",
  "Little-known fact: A secret area in the White House is the <BLANK> room",
  "An invention by Thomas Edison that never caught on",
  "A birthday present you shouldn\u2019t get for your grandmother",
  "What time is it?",
  "Invent a Christmas tradition sure to catch on",
  "A short motto everyone should live by",
  "The best way to start your day",
  "A good improvement to make to Mt. Rushmore",
  "The worst name for a summer camp",
  "The first commandment in the new religion you started",
  "Three things are certain in life: Death, Taxes, and <BLANK>",
  "A faster way to get home from the Land of Oz is to click your heels three times and say <BLANK>.",
  "Something that\u2019s made worse by adding cheese",
  "Which new marshmallow should Lucky Charms cereal introduce?",
  "The perfect song to hum on the toilet",
  "A word that should never follow \u201cBeef\u201d",
  "Something that is currently legal that should be banned",
  "Come up with a name for a rock band made up entirely of baby ducks",
  "We can all agree that <BLANK>",
  "Something you shouldn\u2019t buy off of Craigslist",
  "A bad thing to say to a cop as he writes you a speeding ticket",
  "How far is too far?",
  "If at first you don\u2019t succeed...",
  "The name you would give to a really mopey pig",
  "What robots dream about",
  "What really happened to Amelia Earhart",
  "Something you\u2019d be surprised to see come out of a pimple you pop",
  "Today\u2019s music needs more <BLANK>",
  "Finish this sentence: \u201cWhen I\u2019m rich, my mansion will have a room called The <BLANK> Room.\u201d",
  "The best question to ask God when you meet him",
  "A fun trick to play on your doctor",
  "A bad place for your rocket ship to crash would be The Planet of the <BLANK>",
  "A bad campaign slogan for a congressperson",
  "A unique way to escape from prison",
  "The next product for Matthew McConaughey to endorse",
  "The title of a new YouTube cat video that\u2019s sure to go viral",
  "Come up with the name of a country that doesn\u2019t exist",
  "The best way to keep warm on a cold winter night",
  "The real reason the dinosaurs died",
  "Something you should never put on an open wound",
  "Scientists say erosion, but we all know the Grand Canyon was actually made by <BLANK>",
  "The name of a font nobody would ever use",
  "The best thing about going to prison",
  "The best title for a new national anthem for the USA",
  "A college major you don\u2019t see at many universities",
  "What would make baseball more entertaining to watch?",
  "A little-known fact about Canada",
  "Name a TV drama that\u2019s about a vampire doctor",
  "A name for a brand of designer adult diapers",
  "What\u2019s actually causing global warming?",
  "The first thing you would do after winning the lottery",
  "A name for a really bad Broadway musical",
  "On your wedding night, it would be horrible to find out that the person you married is <BLANK>",
  "The Skittles flavor that just missed the cut",
  "What FDR meant to say was \u201cWe have nothing to fear, but <BLANK>\u201d",
  "A terrible name for a cruise ship",
  "What\u2019s the Mona Lisa smiling about?",
  "The crime you would commit if you could get away with it",
  "Something squirrels probably do when no one is looking",
  "Something you shouldn\u2019t get your significant other for Valentine\u2019s Day",
  "A dangerous thing to do while driving",
  "The best thing about living in an igloo",
  "Using only two words, a new state motto for Texas",
  "The hardest thing about being Batman",
  "Something you shouldn\u2019t wear to a job interview",
  "The #1 reason penguins can\u2019t fly",
  "The name of the reindeer Santa didn\u2019t pick to pull his sleigh",
  "What\u2019s the first thing you would do if you could time travel?",
  "What would you do if you were left alone in the White House for an hour?",
  "Come up with the name of book that would sell a million copies, immediately",
  "A not-very-scary name for a pirate",
  "The name of a pizza place you should never order from",
  "A Starbucks coffee that should never exist",
  "There\u2019s Gryffindor, Ravenclaw, Slytherin, and Hufflepuff, but what\u2019s the Hogwarts house few have ever heard of?",
  "Something you should never use as a scarf",
  "The worst words to say for the opening of a eulogy at a funeral",
  "Come up with a really bad TV show that starts with \u201cBaby\u201d",
  "A great way to kill time at work",
  "What\u2019s wrong with these kids today?",
  "Why does the Tower of Pisa lean?",
  "A great new invention that starts with \u201cAutomatic\u201d",
  "Come up with a really bad football penalty that begins with \u201cIntentional\u201d",
  "You know you\u2019re in for a bad taxi ride when <BLANK>",
  "The terrible fate of the snowman Olaf in a director\u2019s cut of <i>Frozen</i>",
  "Sometimes, after a long day, you just need to <BLANK>",
  "The worst way to spell Mississippi",
  "Give me one good reason why I shouldn\u2019t spank you right now",
  "The best pick-up line for an elderly singles mixer",
  "The best news you could get today",
  "Invent a holiday that you think everyone would enjoy",
  "Usually, it\u2019s bacon, lettuce and tomato, but come up with a BLT you wouldn\u2019t want to eat",
  "The worst thing you could stuff a bed mattress with",
  "A great opening line to start a conversation with a stranger at a party",
  "Something you would like to fill a swimming pool with",
  "Miley Cyrus\u2019 Wi-Fi password, possibly",
  "If you were allowed to name someone else\u2019s baby any weird thing you wanted, what would you name it?",
  "A terrible name for a clown",
  "Miller Lite beer would make a lot of money if they came up with a beer called Miller Lite _____",
  "Okay... fine! What do YOU want to talk about then?!!!",
  "The Katy Perry Super Bowl halftime show would have been better with <BLANK>",
  "Your personal catchphrase if you were on one of those <i>Real Housewives</i> shows",
  "A good fake name to use when checking into a hotel",
  "A vanity license plate a jerk in an expensive car would get",
  "The name of a canine comedy club with puppy stand-up comedians",
  "What\u2019s lurking under your bed when you sleep?",
  "Come up with a name for the most difficult yoga pose known to mankind",
  "One place a finger shouldn\u2019t go",
  "The worst job title that starts with \u201cAssistant\u201d",
  "The grossest thing you\u2019d put in your mouth for $18",
  "The last person you\u2019d consider inviting to your birthday party",
  "Where do you think the beef really is?",
  "A fun trick to play on the Pope",
  "Write a newspaper headline that will really catch people\u2019s attention",
  "Something it\u2019d be fun to throw off the Eiffel Tower",
  "Name the eighth dwarf, who got cut at the last minute",
  "Come up with the name for a new TV show with the word \u201cSpanky\u201d in it",
  "A good place to hide boogers",
  "Come up with a catchier, more marketable name for the Bible",
  "The best thing to use when you\u2019re out of toilet paper",
  "A good way to get fired",
  "The most presidential name you can think of (that isn\u2019t already the name of a president)",
  "Something you should never say to your mother",
  "Where\u2019s the best place to hide from the shadow monsters?",
  "The three ingredients in the worst smoothie ever",
  "Something that would make an awful hat",
  "How many monkeys is too many monkeys?",
  "Something you\u2019d be surprised to see a donkey do",
  "The title you\u2019d come up with if you were writing the Olympics theme song",
  "Name the sequel to <i>Titanic</i> if there were one. <i>Titanic 2: <BLANK></i>",
  "An alternate use for a banana",
  "What you\u2019d guess is an unadvertised ingredient in most hot dogs",
  "Name your new haircutting establishment",
  "An inappropriate thing to do at a cemetery",
  "Like chicken fingers or chicken poppers, a new appetizer name for your fun, theme restaurant: chicken _____",
  "Thing you\u2019d be most surprised to have a dentist find in your mouth",
  "Rename Winnie-the-Pooh to something more appropriate/descriptive",
  "The name of a clothing store for overweight leprechauns",
  "If God has a sense of humor, he welcomes people to heaven by saying, \u201c<BLANK>\u201d",
  "Something that would not work well as a dip for tortilla chips",
  "Name a new movie starring a talking goat who is president of the United States",
  "An item NOT found in Taylor Swift\u2019s purse",
  "Name a new reggae band made up entirely of chickens",
  "Who let the dogs out?",
  "What do vegans taste like?",
  "Make up a word that describes the sound of farting into a bowl of mac & cheese",
  "A new ice cream flavor that no one would ever order",
  "Name a children\u2019s book by someone who hates children",
  "The name of your new plumbing company",
  "The worst name for a robot",
  "The first names of each of your nipples",
  "What John Goodman\u2019s belches smell like",
  "The name of a new perfume by Betty White",
  "One thing never to do on a first date",
  "Ozzy Osbourne\u2019s Twitter password, probably",
  "The most embarrassing name for a dog",
  "The worst thing you could discover in your burrito",
  "Something you\u2019d probably find a lot of in God\u2019s refrigerator",
  "Brand name of a bottled water sold in the land of Oz",
  "The worst family secret that could come out over Thanksgiving dinner",
  "A fun thing to yell as a baby is being born",
  "The name of a toilet paper specifically designed for the Queen of England",
  "A terrible name for a 1930s gangster",
  "Something upsetting you could say to the cable guy as he installs your television service",
  "Come up with a name for a new beer marketed toward babies",
  "A terrible theme for a high school prom",
  "A more environment-friendly alternative to toilet paper",
  "What tattoo should Justin Bieber get next?",
  "What do kittens dream of?",
  "What makes hot dogs taste so good?",
  "A better name for France",
  "The worst thing to find stuck in your teeth",
  "The worst excuse for showing up late to work",
  "The worst thing for an evil witch to turn you into",
  "Jesus\u2019s REAL last words",
  "The biggest downside to living in Hell",
  "Everyone knows that monkeys hate <BLANK>",
  "Name a candle scent designed specifically for Kim Kardashian",
  "If a winning coach gets Gatorade dumped on his head, what should get dumped on the losing coach?",
  "The secret to a happy life",
  "You would never go on a roller coaster called <BLANK>",
  "What two words would passengers never want to hear a pilot say?",
  "The worst name for a race horse",
  "Come up with a three-word sequel to the book \u201cEat, Pray, Love\u201d",
  "You wouldn\u2019t want to share a prison cell with someone named <BLANK>",
  "Superman\u2019s special power that he never tells anyone about",
  "You shouldn\u2019t get a massage at a place called <BLANK>",
  "The least romantic place to propose marriage",
  "A rejected name for the Segway",
];
