export function getRandomRPrompt() {
  return prompts[Math.floor(Math.random() * prompts.length)];
}

const prompts = [
  "The most inappropriate song to hear at a kid\u2019s piano recital",
  "A unique way to amputate your toe",
  "One perk of marrying a serial killer",
  "What a unicorn\u2019s butt smells like",
  "A better name for a corset",
  "A sign that you\u2019re pregnant with an evil baby",
  "How Yogi Bear eventually meets his death",
  "Most people think Julius Caesar said \u201cEt tu, Brute?\u201d when he got stabbed, but what he really said was BLANK",
  "What really pisses off a ghost?",
  "Instead of \u201cHump Day,\u201d we should call Wednesday BLANK",
  "What Michaelangelo said as he chiseled <i>David</i>\u2019s penis",
  "The best cure for a hangover",
  "How do proctologists cheer themselves up?",
  "A disturbing thing to hear your significant other say while sleep-talking",
  "The weirdest place to see an image of the The Virgin Mary",
  "The worst thing that happened on Noah\u2019s Ark",
  "Bad: You\u2019re lost in the woods. Worse: You\u2019re also completely naked. Worst: And you\u2019re also BLANK",
  "How you can tell you\u2019re drinking really cheap wine",
  "An obscure Surgeon General warning that most people don\u2019t know about: \u201cSmoking may cause BLANK\u201d",
  "A lesser-known Medieval torture device: The BLANK",
  "How you can tell it\u2019s time to throw out a pair of underwear",
  "What Wild Bill Hickok named his penis, probably",
  "The crappiest western was <i>Gunfight at the BLANK Corral</i>",
  "Something you should never stuff a bra with",
  "The strangest new military weapon: BLANK-seeking missiles",
  "The polite thing to bring to an orgy in the suburbs",
  "A popular TV show title with the word \u201cpoop\u201d inserted",
  "Yet another practical use for placenta",
  "A surprising new part of the field sobriety test requires you to BLANK to prove you\u2019re not drunk",
  "A name for a sexy turtle",
  "What Little Bo Peep would confess if she got really drunk",
  "The first thought that runs through your head when a lobster clamps onto your genitals",
  "An inappropriate ice sculpture for a wedding reception",
  "The punchline to an off-color <i>Star Wars</i> joke",
  "A shocking find in Clifford the Big Red Dog\u2019s poop",
  "What happens when you finally make eye contact with the crazy person on the subway",
  "An inappropriate thing for a detective to say at a crime scene",
  "The one phrase the NSA is tired of watching us type into Google",
  "Aw screw it... just type in something dirty",
  "Rename any famous work of literature so that it is ruined by the word \u201cbutt\u201d",
  "The secret to being a great kisser",
  "A funny thing to write down on a form when it asks for your sex",
  "A poor substitute for underwear",
  "The worst children\u2019s board game would be \u201cBLANK, BLANK Hippos\u201d",
  "The worst thing to whisper during pillow talk",
  "Something that absolutely doesn\u2019t make you think of a penis on some level",
  "A good sign that your dog is really an a-hole",
  "The strangest reason to get a divorce",
  "Something inappropriate to do at the gym",
  "A secret ability of boobs",
  "The most G-rated term for an erection",
  "The name of a sexy new dance move",
  "What sperm yell as they swim",
  "The Old English term for \u201cvagina\u201d",
  "A strange side effect to hear during a drug commercial",
  "Another use for tampons",
  "The dumbest method of birth control",
  "The name of the website that probably gave your computer a virus",
  "How Garfield the cartoon cat will eventually die",
  "The worst slogan for an erectile dysfunction pill",
  "A crazy thing to find during a colonoscopy",
  "The worst thing you can tell the kids about the death of the family dog",
  "Advice: Never stick your tongue into BLANK",
  "Something a talking doll probably should NOT say when you pull the string",
  "A kinky weird thing that does NOT happen in 50 Shades of Grey (as far as you know)",
  "The biggest complaint of people in Hell",
  "A weirdly enticing subject line for an email in your SPAM folder",
  "A new, completely BS holiday that greeting card companies would make up to sell more cards",
  "Name the next big sexually transmitted disease",
  "What happens to circumcision skin",
  "What dogs think when they see people naked",
  "The title of the most boring porno ever",
  "Something Godzilla does when he\u2019s drunk",
  "A good name for an elderly nudist colony",
  "An inappropriate thing to say via skywriting",
  "A good name for a sex robot",
  "A cute name for hemorrhoids",
  "Something in a weirdo\u2019s bedroom",
  "The worst song to play when stripping for your lover",
  "A movie that could use some nudity",
  "Pick any city name and make it sound dirty",
  "An item on every pervert\u2019s grocery list",
  "The password to the secret, high-society sex club down the street",
  "You know you\u2019re really drunk when...",
  "What they call pooping in the Land of Oz",
  "What Santa does with a dead elf",
  "The least popular item in the Victoria\u2019s Secret catalog",
  "The worst way to remove pubic hair",
  "A Facebook status you don\u2019t want your grandparents to see",
  "A tourist attraction in Hell",
  "A new slang term for impotence",
  "A weird thing to find in your grandparents\u2019 bedside table",
  "The name of a cocktail for hillbillies",
  "What a dog sext message might say",
  "The 6,077th layer of Hell is reserved for BLANK",
  "An image that would make the Sistine Chapel's ceiling look more badass",
  "What deer would use for bait if they hunted hunters",
  "A punch line for a joke that would make children cry",
  "A brand name for a medication that intentionally CAUSES male impotence",
  "Make up a schoolyard game that children should never play at recess",
  "A magazine that should never have a nude centerfold",
  "An inappropriate theme for a set of kids\u2019 pajamas",
  "Another name for a rectal thermometer",
  "The most bitching thing you can airbrush on your van",
  "The Seven Deadly Sins are lust, gluttony, greed, envy, pride, wrath, and sloth. The Eighth Deadly Sin is...",
  "Come up with a name for a fast food chain that only serves rabbit meat",
  "Something fun to do with your kidney stones after you pass them",
  "An unusual object to bludgeon someone to death with",
  "The least-threatening name for a serial killer: The Boston BLANK",
  "The first inductee of the A-hole Hall of Fame ",
  "A name for a new cereal that\u2019s for adults only",
  "Make up a curse word",
  "The celebrity you\u2019d eat first if you were a cannibal, and the side dish you\u2019d eat them with",
  "Santa Claus would be a bigger badass if his sleigh were driven by eight tiny\u2026",
  "A good name for a restaurant that serves animals with the faces still on them ",
  "A name for a board game designed to give children nightmares ",
  "The worst person to narrate the audiobook of <i>Fifty Shades of Grey</i>",
  "A good name for an erotic bakery",
  "What the Statue of Liberty is hiding beneath that robe",
  "There\u2019s only one time that murder is acceptable and that is when BLANK",
  "Take any well-known restaurant and slightly change its name to something inappropriate",
  "A catchy name for a sperm bank",
  "A bad place to skinny-dip",
  "A bad thing to yell during church",
  "The unsexiest thought you can have",
  "Take any U.S. president\u2019s name and turn it into something inappropriate",
  "A great name to have on a fake I.D.",
  "The name of an all-male version of Hooters",
  "Two people from history that should definitely have sex",
  "The coolest way to die",
  "A little-known nickname for New Orleans",
  "Come up with a title for an adult version of any classic video game",
  "Come up with a great title for the next awkward teen sex movie",
  "Come up with a name for a beer made especially for monkeys",
  "The worst way to be murdered",
  "A better name for testicles",
  "Invent a family-friendly replacement word that you could say instead of an actual curse word",
  "Where do babies come from?",
  "A fun thing to think about during mediocre sex",
  "Something you should never stick up your butt",
  "A good catchphrase to yell every time you finish pooping",
  "Make up the title of a movie that is based on the first time you had sex",
  "A great name for a nude beach in Alaska",
  "A good stage name for a chimpanzee stripper",
  "The best place to bury all those bodies",
  "If we can\u2019t afford to bury or cremate you, what should we do with your body?",
  "Come up with a name for a new, very manly cocktail",
  "Make up a name for a silent-film porno from the 1920s",
  "Something you should not whisper to your grandmother",
  "The worst thing that could jump out of a bachelor party cake",
  "What aliens do with you after the anal probe",
  "You should never give alcohol to BLANK",
  "A great brand name for extra-extra-large condoms",
  "What the genitalia on a Tofurky is called",
];
