export function getRandomPicturePrompt() {
  return prompts[Math.floor(Math.random() * prompts.length)];
}

const prompts = [
  "The most valuable thing that the no one will buy",
  "This is not what it seems",
  "The expression you make when you find a $100 bill hidden inside your Nintendo 64",
  "The expression you make when your ice cream drops from your cone",
  "A close-up of something that is not what it seems",
  "Ghandi died for this",
  "What is for lunch",
  "The yellowest thing",
  "The most serious book",
  "The most boring thing",
  "The most awesome thing",
  "The most sad thing",
  "The most threatening thing",
  "The most strong thing",
  "The most practical thing",
  "The most cute thing",
  "The most amusing thing",
  "The most wonderful thing",
  "The most impressive thing",
  "The most famous thing",
  "The most ill-informed thing",
  "The most overrated thing",
  "The most stimulating thing",
  "The most suspicious thing",
  "The most tedious thing",
  "The most wooden thing",
  "The most amused thing",
  "The most sick thing",
  "The most unusual thing",
  "The most nosy thing",
  "The most nutty thing",
  "The most ultra thing",
  "The most sweltering thing",
  "The most watery thing",
  "The most fearful thing",
  "The most dysfunctional thing",
  "The most crazy thing",
  "The most agonizing thing",
  "The most windy thing",
  "The most scandalous thing",
  "The most imminent thing",
  "The most nutritious thing",
];
